use crate::{Generator, GeneratedFile};
use anyhow::Result;
use std::path::Path;

/// Generates git hooks (pre-commit, pre-push) that run process checks
pub struct GitHooksGenerator;

impl Generator for GitHooksGenerator {
    fn name(&self) -> &'static str {
        "git-hooks"
    }

    fn description(&self) -> &'static str {
        "Generate pre-commit and pre-push git hooks"
    }

    fn generate(&self, project_root: &Path) -> Result<Vec<GeneratedFile>> {
        let hooks_dir = project_root.join(".git/hooks");
        let mut files = Vec::new();

        // Detect project type for appropriate commands
        let has_cargo = project_root.join("Cargo.toml").exists();
        let has_package_json = project_root.join("package.json").exists();
        let has_pyproject = project_root.join("pyproject.toml").exists();

        let mut pre_commit_checks = vec![
            "echo '🔍 Running pre-commit checks...'".to_string(),
        ];

        let mut pre_push_checks = vec![
            "echo '🔍 Running pre-push checks...'".to_string(),
        ];

        if has_cargo {
            pre_commit_checks.push("cargo fmt --check || { echo '❌ Format check failed'; exit 1; }".to_string());
            pre_commit_checks.push("cargo clippy --all-targets -- -D warnings || { echo '❌ Lint failed'; exit 1; }".to_string());
            pre_push_checks.push("cargo test || { echo '❌ Tests failed'; exit 1; }".to_string());
        }

        if has_package_json {
            pre_commit_checks.push("npx eslint . || { echo '❌ Lint failed'; exit 1; }".to_string());
            pre_push_checks.push("npm test || { echo '❌ Tests failed'; exit 1; }".to_string());
        }

        if has_pyproject {
            pre_commit_checks.push("ruff check . || { echo '❌ Lint failed'; exit 1; }".to_string());
            pre_push_checks.push("pytest || { echo '❌ Tests failed'; exit 1; }".to_string());
        }

        // Process-specific checks
        pre_commit_checks.push("# Process CLI sensitive info check".to_string());
        pre_commit_checks.push("if command -v process &> /dev/null; then process check sensitive 2>/dev/null || true; fi".to_string());

        pre_commit_checks.push("echo '✅ Pre-commit checks passed'".to_string());
        pre_push_checks.push("echo '✅ Pre-push checks passed'".to_string());

        let pre_commit = format!("#!/bin/sh\n# Generated by process-cli\n# To skip: git commit --no-verify\n\n{}\n", pre_commit_checks.join("\n"));
        let pre_push = format!("#!/bin/sh\n# Generated by process-cli\n# To skip: git push --no-verify\n\n{}\n", pre_push_checks.join("\n"));

        let overwrite_commit = hooks_dir.join("pre-commit").exists();
        let overwrite_push = hooks_dir.join("pre-push").exists();

        files.push(GeneratedFile {
            path: ".git/hooks/pre-commit".to_string(),
            content: pre_commit,
            overwritten: overwrite_commit,
        });

        files.push(GeneratedFile {
            path: ".git/hooks/pre-push".to_string(),
            content: pre_push,
            overwritten: overwrite_push,
        });

        Ok(files)
    }
}
