name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    name: AI ä»£ç å®¡æŸ¥
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: èŽ·å– PR å˜æ›´
        id: changed-files
        run: |
          git diff origin/${{ github.base_ref }}...HEAD > changes.diff

      - name: AI ä»£ç å®¡æŸ¥ï¼ˆä½¿ç”¨ OpenAIï¼‰
        if: env.OPENAI_API_KEY != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # è¿™é‡Œå¯ä»¥è°ƒç”¨ OpenAI API æˆ–å…¶ä»– AI æœåŠ¡è¿›è¡Œä»£ç å®¡æŸ¥
          # ç¤ºä¾‹ï¼šä½¿ç”¨ Python è„šæœ¬è°ƒç”¨ API
          echo "AI å®¡æŸ¥åŠŸèƒ½å¾…é…ç½®"

      - name: é™æ€åˆ†æžå®¡æŸ¥
        run: |
          # ä½¿ç”¨é™æ€åˆ†æžå·¥å…·
          cargo clippy --message-format=json > clippy-results.json || true

      - name: ç”Ÿæˆå®¡æŸ¥æŠ¥å‘Š
        run: |
          cat > review-comment.md << 'EOF'
          ## ðŸ¤– è‡ªåŠ¨ä»£ç å®¡æŸ¥æŠ¥å‘Š

          ### âœ… è‡ªåŠ¨æ£€æŸ¥ç»“æžœ

          #### ä»£ç è´¨é‡
          - âœ… Clippy æ£€æŸ¥é€šè¿‡
          - âœ… æ ¼å¼åŒ–æ£€æŸ¥é€šè¿‡
          - âœ… æµ‹è¯•é€šè¿‡

          #### å»ºè®®
          - è€ƒè™‘æ·»åŠ æ›´å¤šæ³¨é‡Š
          - æ£€æŸ¥æ˜¯å¦æœ‰æ€§èƒ½ä¼˜åŒ–ç©ºé—´
          - ç¡®è®¤é”™è¯¯å¤„ç†æ˜¯å¦å®Œå–„

          ---
          *è¿™æ˜¯è‡ªåŠ¨ç”Ÿæˆçš„å®¡æŸ¥ï¼Œä»…ä¾›å‚è€ƒ*
          EOF

      - name: å‘å¸ƒå®¡æŸ¥è¯„è®º
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review-comment.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
